# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Yasi
tagline:          'I love you'
description:      'A website I made for the georgeous Yasmin George <3.'
url:              https://ryancranie.com
baseurl:          /yasi

author:
  name:           'Ryan Cranie'
  url:            https://ryancranie.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
